modLoader="javafml"
loaderVersion="[1,)"
license="BSD (3 Clause)"
issueTrackerURL="https://github.com/gigaherz/JsonThings/issues"

[[mods]]
modId="jsonthings"
version="${file.jarVersion}"
displayName="Json Things"
logoFile="jsonthings-logo.png"
description='''
Things, in JSON sauce.
'''
authors="gigaherz"
displayURL="https://github.com/gigaherz/JsonThings"

[[mixins]]
config = "jsonthings.mixins.json"

[[dependencies.jsonthings]]
   modId="neoforge"
   type="required"
   versionRange="[20.2.4-beta,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.jsonthings]]
   modId="minecraft"
   type="required"
   versionRange="[1.20.2,1.21)"
   ordering="NONE"
   side="BOTH"
[[dependencies.jsonthings]]
   modId="rhino"
   type="optional"
   versionRange="[1902.2,)"
   ordering="NONE"
   side="BOTH"