modLoader="javafml"
loaderVersion="[46,)"
license="BSD (3 Clause)"
issueTrackerURL="https://github.com/gigaherz/JsonThings/issues"

[[mods]]
modId="jsonthings"
version="${file.jarVersion}"
displayName="Json Things"
logoFile="jsonthings-logo.png"
description='''
Things, in JSON sauce.
'''
authors="gigaherz"
displayURL="https://github.com/gigaherz/JsonThings"

[[dependencies.jsonthings]]
   modId="forge"
   mandatory=true
   versionRange="[46.0.12,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.jsonthings]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20,1.21)"
   ordering="NONE"
   side="BOTH"
[[dependencies.jsonthings]]
   modId="rhino"
   mandatory=false
   versionRange="[1902.2,)"
   ordering="NONE"
   side="BOTH"