modLoader="javafml"
loaderVersion="[1,)"
license="BSD (3 Clause)"
issueTrackerURL="https://github.com/gigaherz/JsonThings/issues"

[[mods]]
modId="jsonthings"
version="${file.jarVersion}"
displayName="Json Things"
logoFile="jsonthings-logo.png"
description='''
Things, in JSON sauce.
'''
authors="gigaherz"
displayURL="https://github.com/gigaherz/JsonThings"

[[mixins]]
config = "jsonthings.mixins.json"

[[dependencies.jsonthings]]
   modId="neoforge"
   type="required"
   versionRange="[21.0.42-beta,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.jsonthings]]
   modId="minecraft"
   type="required"
   versionRange="[1.21,1.22)"
   ordering="NONE"
   side="BOTH"